ALTER TYPE "SocialPlatform" ADD VALUE IF NOT EXISTS 'THREADS';
ALTER TYPE "SocialPlatform" ADD VALUE IF NOT EXISTS 'YOUTUBE_SHORTS';
ALTER TYPE "SocialPreferredFormat" ADD VALUE IF NOT EXISTS 'TEXT';
