ALTER TYPE "SocialAccountStrategyGoal" ADD VALUE IF NOT EXISTS 'VISIT_RESERVATION';
ALTER TYPE "SocialAccountStrategyGoal" ADD VALUE IF NOT EXISTS 'REPEAT';
ALTER TYPE "SocialAccountStrategyGoal" ADD VALUE IF NOT EXISTS 'TRUST_EXPERTISE';
