import type { BunshinEditorProps } from './editor';
import type { BunshinPageData } from './bunshin-page-data';

export function buildBunshinEditorProps(
  workspaceId: string,
  data: BunshinPageData,
): BunshinEditorProps {
  const {
    bunshin,
    personalityVersions,
    personalityLearningProposals,
    owned,
    granted,
    memories,
    socialCapabilityStatus,
    lineNotificationPreference,
    socialProfiles,
    socialStrategies,
    contentPillars,
    weeklyPlans,
    dailyMissions,
    missionDecisions,
    missionOutcomes,
    missionVariants,
    variantPointCost,
    rewardsPilotActive,
    progress,
    motivation,
    localDate,
  } = data;

  return {
    workspaceId,
    bunshin,
    personalityVersions: personalityVersions.map(
      ({
        id,
        version,
        source,
        changeReason,
        tone,
        formality,
        energyLevel,
        expertiseLevel,
        sentenceStyle,
        firstPerson,
        forbiddenExpressions,
        preferredExpressions,
        visualDirection,
        facePolicy,
        createdAt,
      }) => ({
        id,
        version,
        source,
        changeReason,
        tone,
        formality,
        energyLevel,
        expertiseLevel,
        sentenceStyle,
        firstPerson,
        forbiddenExpressions,
        preferredExpressions,
        visualDirection,
        facePolicy,
        createdAt: createdAt.toISOString(),
      }),
    ),
    personalityLearningProposals: personalityLearningProposals.map((proposal) => ({
      id: proposal.id,
      status: proposal.status,
      proposedContent: proposal.proposedContent,
      reason: proposal.reason,
      evidenceCount: proposal.evidenceIds.length,
      createdAt: proposal.createdAt.toISOString(),
    })),
    knowledge: owned.map(({ id, title, type }) => ({
      id,
      title,
      type,
      granted: granted.some((item) => item.id === id),
    })),
    memories: memories.map(({ id, type, content, summary, confidence, importance, active }) => ({
      id,
      type,
      content,
      summary,
      confidence,
      importance,
      active,
    })),
    socialCapabilityStatus,
    socialProfiles: socialProfiles.map(
      ({
        id,
        platform,
        handle,
        profileUrl,
        purpose,
        postingFrequency,
        preferredFormats,
        defaultAssistanceLevel,
        status,
      }) => ({
        id,
        platform,
        handle,
        profileUrl,
        purpose,
        postingFrequency,
        preferredFormats,
        defaultAssistanceLevel,
        status,
      }),
    ),
    socialStrategies: socialStrategies.map(
      ({
        id,
        socialProfileId,
        platform,
        concept,
        positioning,
        targetSummary,
        version,
        status,
      }) => ({
        id,
        socialProfileId,
        platform,
        concept,
        positioning,
        targetSummary,
        version,
        status,
      }),
    ),
    contentPillars: contentPillars.map(({ id, title, description, weight, active }) => ({
      id,
      title,
      description,
      weight,
      active,
    })),
    weeklyPlans: weeklyPlans.map(
      ({ id, weekStartDate, timezone, strategySummary, status, items }) => ({
        id,
        weekStartDate,
        timezone,
        strategySummary,
        status,
        items: items.map(
          ({
            id: itemId,
            scheduledDate,
            contentPillarId,
            goal,
            angle,
            recommendedFormat,
            notes,
            campaignId,
            classification,
          }) => ({
            id: itemId,
            scheduledDate,
            contentPillarId,
            goal,
            angle,
            recommendedFormat,
            notes,
            campaignId,
            classification,
          }),
        ),
      }),
    ),
    dailyMissions: dailyMissions.map(
      (
        {
          id,
          missionDate,
          status,
          format,
          assistanceLevel,
          estimatedMinutes,
          topic,
          angle,
          reason,
          campaignId,
          classification,
          qualityScore,
          content,
          socialProfileId,
          trendContext,
          linkUsage,
        },
        index,
      ) => ({
        id,
        missionDate,
        status,
        format,
        assistanceLevel,
        estimatedMinutes,
        topic,
        angle,
        reason,
        campaignId,
        classification,
        qualityScore,
        content,
        decision: missionDecisions[index]!.decision,
        rejectionReason: missionDecisions[index]!.rejectionReason,
        platform:
          socialProfiles.find((profile) => profile.id === socialProfileId)?.platform ?? null,
        postedAt: missionOutcomes[index]!.post?.postedAt.toISOString() ?? null,
        feedback: missionOutcomes[index]!.feedback?.rating ?? null,
        trendContext: trendContext
          ? {
              whyNow: trendContext.snapshot.candidate.whyNow,
              fitReason: trendContext.snapshot.candidate.fitReason,
            }
          : null,
        externalLinkUsage: linkUsage
          ? { ...linkUsage, expiresAt: linkUsage.expiresAt?.toISOString() ?? null }
          : null,
        variants: missionVariants[index]!.map(
          ({ id: variantId, sequence, content: variantContent, qualityScore, selectedAt }) => ({
            id: variantId,
            sequence,
            content: variantContent,
            qualityScore,
            selectedAt: selectedAt?.toISOString() ?? null,
          }),
        ),
      }),
    ),
    variantPointCost,
    rewardsPilotActive,
    progress,
    motivation,
    localDate,
    lineNotificationPreference: {
      enabled: lineNotificationPreference.enabled,
      consentGranted: lineNotificationPreference.notificationConsentAt !== null,
      localTime: lineNotificationPreference.localTime,
      timezone: lineNotificationPreference.timezone,
      frequency: lineNotificationPreference.frequency,
      quietHoursStart: lineNotificationPreference.quietHoursStart,
      quietHoursEnd: lineNotificationPreference.quietHoursEnd,
      pausedUntil: lineNotificationPreference.pausedUntil
        ? lineNotificationPreference.pausedUntil.toISOString()
        : null,
      reminderEnabled: lineNotificationPreference.reminderEnabled,
    },
  };
}
