import type { TrainingActionKey } from './index';
import { AI_TRAINING_MISSION_SKILLS, type TrainingSkillKey } from './skill-evaluation';

export const AI_TRAINING_MISSION_QUALITY_VERSION = 'AI_TRAINING_MISSION_QUALITY_V1';

export type TrainingMissionDifficulty = 'EASY' | 'STANDARD' | 'CHALLENGE';

export type TrainingMissionQualityDefinition = {
  key: TrainingActionKey;
  title: string;
  phaseKey: 'FOUNDATION' | 'PRACTICE' | 'APPLICATION';
  learningObjective: string;
  businessScenario: string;
  task: string;
  constraints: readonly string[];
  successCriteria: readonly string[];
  commonMistakes: readonly string[];
  evaluationCriteria: readonly string[];
  estimatedMinutes: number;
  difficulty: TrainingMissionDifficulty;
  reviewMissionKey: TrainingActionKey | null;
  nextCandidates: readonly TrainingActionKey[];
  skillKeys: readonly TrainingSkillKey[];
};

const baseDefinitions = [
  {
    key: 'AI_BASIC',
    title: 'AIへ仕事を頼む基本',
    phaseKey: 'FOUNDATION',
    learningObjective: 'AIに任せる作業と、人が確認する部分を区別できる',
    businessScenario: '今日の仕事から、AIに下書きを任せられる作業を1つ選びます。',
    task: 'AIに任せたい作業と、最後に自分で確認することを1つずつ書いてください。',
    constraints: ['実際の仕事を1つ選ぶ', '個人情報や社外秘は書かない', '人が確認する項目を含める'],
    successCriteria: ['作業内容が具体的', 'AIと人の役割が分かれている'],
    commonMistakes: ['「仕事を手伝って」だけで終わる', 'AIの回答を確認せず使う前提にする'],
    evaluationCriteria: ['対象作業の具体性', '人による確認工程の有無'],
    estimatedMinutes: 5,
    difficulty: 'EASY',
    reviewMissionKey: 'AI_BASIC',
    nextCandidates: ['CHATGPT_BASIC'],
  },
  {
    key: 'CHATGPT_BASIC',
    title: 'ChatGPTへ具体的に依頼する',
    phaseKey: 'FOUNDATION',
    learningObjective: '目的と依頼内容を1回の指示で伝えられる',
    businessScenario: '仕事中にChatGPTへ最初の依頼を送る場面です。',
    task: '「何のために」「何をしてほしいか」が分かる依頼文を書いてください。',
    constraints: ['目的を1つ書く', '依頼する作業を1つ書く', '実在する個人名は使わない'],
    successCriteria: ['目的が明確', '依頼内容が具体的'],
    commonMistakes: ['質問だけで目的がない', '複数の作業を一度に頼む'],
    evaluationCriteria: ['目的の明確さ', '依頼範囲の具体性'],
    estimatedMinutes: 5,
    difficulty: 'EASY',
    reviewMissionKey: 'CHATGPT_BASIC',
    nextCandidates: ['PROMPT_BASIC'],
  },
  {
    key: 'PROMPT_BASIC',
    title: '仕事で使える指示を組み立てる',
    phaseKey: 'FOUNDATION',
    learningObjective: '背景・目的・依頼を分けて指示できる',
    businessScenario: '同僚に説明する代わりに、AIへ仕事の背景から伝えます。',
    task: '背景、目的、依頼内容の3点を含むAIへの指示を書いてください。',
    constraints: ['3点を区別して書く', '依頼は1つに絞る'],
    successCriteria: ['背景がある', '目的がある', '実行可能な依頼がある'],
    commonMistakes: ['依頼だけを書く', '背景と目的が同じ内容になる'],
    evaluationCriteria: ['指示構造', '背景設定', '依頼の実行可能性'],
    estimatedMinutes: 5,
    difficulty: 'EASY',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['PROMPT_CONDITION'],
  },
  {
    key: 'PROMPT_CONDITION',
    title: '必要な条件を指定する',
    phaseKey: 'FOUNDATION',
    learningObjective: '回答の品質を左右する条件を具体的に指定できる',
    businessScenario: 'AIの回答が長すぎる、または用途に合わない状態を改善します。',
    task: '対象、長さ、文体、注意点から2つ以上を選び、指示へ追加してください。',
    constraints: ['条件を2つ以上含める', '数値にできる条件は数値で示す'],
    successCriteria: ['条件が具体的', '目的と条件が矛盾しない'],
    commonMistakes: ['「いい感じに」だけで指定する', '条件を増やしすぎて矛盾する'],
    evaluationCriteria: ['条件指定', '測定可能性', '条件の一貫性'],
    estimatedMinutes: 5,
    difficulty: 'EASY',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['PROMPT_FORMAT'],
  },
  {
    key: 'PROMPT_FORMAT',
    title: '使いやすい出力形式を指定する',
    phaseKey: 'FOUNDATION',
    learningObjective: '仕事でそのまま確認しやすい出力形式を指定できる',
    businessScenario: 'AIの回答をコピー後に並べ替える手間を減らします。',
    task: '箇条書き、表、メール文のいずれかを選び、必要な項目と順番を指定してください。',
    constraints: ['形式を明記する', '必要な項目を2つ以上示す'],
    successCriteria: ['完成形が想像できる', '用途に合う形式になっている'],
    commonMistakes: ['「分かりやすく」だけで終わる', '用途に合わない形式を選ぶ'],
    evaluationCriteria: ['出力制御', '必要項目の明確さ', '業務での使いやすさ'],
    estimatedMinutes: 5,
    difficulty: 'EASY',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['EMAIL_WRITING', 'DOCUMENT_SUMMARY', 'SALES_EMAIL', 'OFFICE_MINUTES'],
  },
  {
    key: 'PROMPT_REVIEW',
    title: '指示を見直して改善する',
    phaseKey: 'FOUNDATION',
    learningObjective: '不足している背景・条件・形式を見つけて修正できる',
    businessScenario: '期待と違ったAI回答を、指示の改善でやり直します。',
    task: '前回の指示を、目的・背景・条件・出力形式が分かる形に書き直してください。',
    constraints: ['修正した点を1つ意識する', '答えそのものではなくAIへの指示を書く'],
    successCriteria: ['前回より具体的', '目的・条件・形式がそろっている'],
    commonMistakes: ['同じ指示を言い換えるだけ', 'AIへ正解を直接書いてしまう'],
    evaluationCriteria: ['改善の具体性', '指示構造', '不足条件の補完'],
    estimatedMinutes: 4,
    difficulty: 'EASY',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['PROMPT_CONDITION', 'PROMPT_FORMAT'],
  },
  {
    key: 'EMAIL_WRITING',
    title: '社内メールをAIで作る',
    phaseKey: 'PRACTICE',
    learningObjective: '相手・目的・要点・文体を指定してメールを作れる',
    businessScenario: '同僚へ締切変更を伝える社内メールを作ります。',
    task: '締切を2日延長したい場面で、理由と新しい期限を伝えるメール作成指示を書いてください。',
    constraints: ['件名あり', '200文字以内', '新しい期限を明記', '丁寧で簡潔'],
    successCriteria: ['相手と目的が明確', '期限が一つに定まる', '必要な配慮がある'],
    commonMistakes: ['期限を書かない', '理由が長すぎる', '依頼内容が曖昧'],
    evaluationCriteria: ['背景設定', '条件指定', '文体指定', '業務実用性'],
    estimatedMinutes: 8,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['DOCUMENT_PROOFREAD'],
  },
  {
    key: 'DOCUMENT_SUMMARY',
    title: '長文を業務向けに要約する',
    phaseKey: 'PRACTICE',
    learningObjective: '読み手と用途に合わせて残す情報を指定できる',
    businessScenario: '長い社内連絡を、上司が1分で確認できる形にします。',
    task: '決定事項・期限・担当者を残し、300文字以内で要約させる指示を書いてください。',
    constraints: ['300文字以内', '決定事項・期限・担当者を残す', '推測を加えない'],
    successCriteria: ['読み手が明確', '残す情報が指定されている', '禁止事項がある'],
    commonMistakes: ['「要約して」だけで終わる', '重要情報の優先順位がない'],
    evaluationCriteria: ['要約目的', '情報選択', '制約指定', '正確性への配慮'],
    estimatedMinutes: 8,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['OFFICE_MINUTES', 'DOCUMENT_PROOFREAD'],
  },
  {
    key: 'DOCUMENT_PROOFREAD',
    title: '文章を目的に合わせて整える',
    phaseKey: 'PRACTICE',
    learningObjective: '読み手と文体を指定し、意味を変えずに校正させられる',
    businessScenario: '社外向け案内文を、丁寧で読みやすい文章へ整えます。',
    task: '内容を変えず、専門用語を減らし、丁寧語で校正させる指示を書いてください。',
    constraints: ['事実を追加しない', '意味を変えない', '修正理由も出す'],
    successCriteria: ['読み手が明確', '変更禁止事項がある', '確認方法が指定されている'],
    commonMistakes: ['文体だけ指定する', '事実追加を防ぐ指示がない'],
    evaluationCriteria: ['読み手設定', '変更範囲', '出力制御', '安全性'],
    estimatedMinutes: 8,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['IDEA_GENERATION'],
  },
  {
    key: 'IDEA_GENERATION',
    title: '条件に合うアイデアを出す',
    phaseKey: 'PRACTICE',
    learningObjective: '目的・対象・制約を示して実行可能な案を得られる',
    businessScenario: '追加予算を使わず、社内の業務時間を減らす案を考えます。',
    task: '対象業務を1つ決め、予算0円・1週間以内に試せる改善案を5つ求める指示を書いてください。',
    constraints: ['案は5つ', '予算0円', '1週間以内に試せる', '優先順位を付ける'],
    successCriteria: ['対象が具体的', '実行条件が明確', '比較できる出力になっている'],
    commonMistakes: ['テーマが広すぎる', '実行条件がない'],
    evaluationCriteria: ['課題設定', '条件指定', '出力制御', '実行可能性'],
    estimatedMinutes: 8,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['MANAGER_IMPROVEMENT'],
  },
  {
    key: 'SALES_EMAIL',
    title: '顧客に合わせた営業メールを作る',
    phaseKey: 'PRACTICE',
    learningObjective: '顧客像・課題・価値・CTAを指定できる',
    businessScenario: '問い合わせ後、まだ商談していない顧客へ初回メールを送ります。',
    task: '顧客の課題を1つ想定し、押し売り感を抑えた初回営業メールを作る指示を書いてください。',
    constraints: ['件名あり', '250文字以内', 'CTAは1つ', '誇大表現を使わない'],
    successCriteria: ['顧客課題が具体的', '提供価値が明確', '次の行動が1つ'],
    commonMistakes: ['商品説明だけになる', 'CTAが複数ある', '根拠のない効果を書く'],
    evaluationCriteria: ['顧客理解', '価値提案', '条件指定', 'CTAの明確さ'],
    estimatedMinutes: 10,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_REVIEW',
    nextCandidates: ['SALES_HEARING'],
  },
  {
    key: 'SALES_HEARING',
    title: '商談ヒアリングを準備する',
    phaseKey: 'PRACTICE',
    learningObjective: '顧客の現状・課題・判断条件を確認する質問を作れる',
    businessScenario: '30分の初回商談で、提案前に顧客理解を深めます。',
    task: '顧客像と商談目的を示し、現状・課題・期限・決裁の質問を作る指示を書いてください。',
    constraints: ['質問は8個以内', '誘導質問を避ける', '質問の目的も表示'],
    successCriteria: ['質問領域が偏らない', '商談時間に収まる', '提案判断に使える'],
    commonMistakes: ['商品へ誘導する質問だけ', '質問数が多すぎる'],
    evaluationCriteria: ['顧客設定', '質問設計', '制約指定', '実務適合性'],
    estimatedMinutes: 10,
    difficulty: 'STANDARD',
    reviewMissionKey: 'SALES_HEARING',
    nextCandidates: ['SALES_PROPOSAL'],
  },
  {
    key: 'SALES_PROPOSAL',
    title: '顧客課題に沿った提案骨子を作る',
    phaseKey: 'APPLICATION',
    learningObjective: '課題・解決策・根拠・次の行動を一貫させられる',
    businessScenario: 'ヒアリング済み顧客へ5枚の提案書を準備します。',
    task: '顧客課題と制約を示し、5枚構成の提案書骨子を作る指示を書いてください。',
    constraints: ['5枚構成', '各ページに見出しと要点', '不明な数値を創作しない', 'CTAは1つ'],
    successCriteria: ['課題と解決策が対応', '根拠が確認可能', '流れが一貫している'],
    commonMistakes: ['自社紹介が中心', '課題と施策がつながらない', '数値を創作する'],
    evaluationCriteria: ['論理構成', '顧客課題との整合', '安全性', '行動提案'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'SALES_EMAIL',
    nextCandidates: ['SALES_FOLLOW_UP'],
  },
  {
    key: 'SALES_FOLLOW_UP',
    title: '押し売り感のないフォロー文を作る',
    phaseKey: 'APPLICATION',
    learningObjective: '状況に配慮しながら次の行動を1つ提示できる',
    businessScenario: '見積送付後3日、返信がない顧客へ確認します。',
    task: '見積確認の負担を下げ、催促感を抑えたフォローメール作成指示を書いてください。',
    constraints: ['件名あり', '200文字以内', 'CTAは1つ', '急かす表現を避ける'],
    successCriteria: ['状況説明が簡潔', '相手への配慮がある', '次の行動が明確'],
    commonMistakes: ['返信期限を一方的に決める', 'CTAがない', '謝罪しすぎる'],
    evaluationCriteria: ['状況設定', 'Tone指定', '制約指定', 'CTAの明確さ'],
    estimatedMinutes: 8,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'SALES_EMAIL',
    nextCandidates: ['WAIT'],
  },
  {
    key: 'OFFICE_MINUTES',
    title: '行動につながる議事録を作る',
    phaseKey: 'PRACTICE',
    learningObjective: '決定事項・担当・期限・未決事項を整理させられる',
    businessScenario: '60分の会議メモを、参加者が確認できる議事録にします。',
    task: '決定事項、担当者、期限、未決事項を分けて整理する指示を書いてください。',
    constraints: ['表形式', '発言を創作しない', '不明項目は「要確認」', '要約は500文字以内'],
    successCriteria: ['4項目が分離', '事実と要確認が区別', '次の行動が分かる'],
    commonMistakes: ['会話の要約だけになる', '担当と期限が混ざる', '不足情報を補完する'],
    evaluationCriteria: ['情報整理', '出力制御', '正確性への配慮', '実務実用性'],
    estimatedMinutes: 10,
    difficulty: 'STANDARD',
    reviewMissionKey: 'DOCUMENT_SUMMARY',
    nextCandidates: ['OFFICE_DOCUMENT'],
  },
  {
    key: 'OFFICE_DOCUMENT',
    title: '読み手に伝わる社内文書を作る',
    phaseKey: 'PRACTICE',
    learningObjective: '読み手・目的・必要項目を示して文書を作れる',
    businessScenario: '新しい申請手順を全社員へ案内します。',
    task: '対象者、開始日、変更点、問い合わせ先を含む社内案内文の作成指示を書いてください。',
    constraints: ['見出しあり', '400文字以内', '専門用語を避ける', '不明情報を創作しない'],
    successCriteria: ['読み手と目的が明確', '必要項目がそろう', '行動が分かる'],
    commonMistakes: ['背景説明が長い', '開始日や問い合わせ先がない'],
    evaluationCriteria: ['読み手設定', '必要情報', '出力制御', '明瞭さ'],
    estimatedMinutes: 10,
    difficulty: 'STANDARD',
    reviewMissionKey: 'EMAIL_WRITING',
    nextCandidates: ['OFFICE_EXCEL'],
  },
  {
    key: 'OFFICE_EXCEL',
    title: 'Excel作業をAIに相談する',
    phaseKey: 'APPLICATION',
    learningObjective: '表の構造と期待結果を安全に説明できる',
    businessScenario: '売上一覧から担当者別合計を出す方法をAIへ相談します。',
    task: '列名とサンプル値を匿名化して示し、必要なExcel式と手順を求める指示を書いてください。',
    constraints: ['個人情報を匿名化', '列名を明記', '期待結果を例示', '確認手順も求める'],
    successCriteria: ['入力構造が分かる', '完成形が分かる', '検算方法がある'],
    commonMistakes: ['実データを貼る', '「集計して」だけで終わる', 'Excel版を示さない'],
    evaluationCriteria: ['データ説明', 'プライバシー配慮', '期待結果', '検証方法'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'PROMPT_FORMAT',
    nextCandidates: ['OFFICE_DATA'],
  },
  {
    key: 'OFFICE_DATA',
    title: 'データ整理ルールを作る',
    phaseKey: 'APPLICATION',
    learningObjective: '分類基準と例外処理を明確に指定できる',
    businessScenario: '表記揺れのある問い合わせ一覧を分類します。',
    task: '匿名のサンプルを使い、分類名・判定基準・不明時の扱いを決める指示を書いてください。',
    constraints: ['分類は5種類以内', '判定基準を明記', '不明は別扱い', '元データを変更しない'],
    successCriteria: ['分類が重複しにくい', '例外処理がある', '結果を確認できる'],
    commonMistakes: ['分類名だけを指定', '不明データを無理に分類する'],
    evaluationCriteria: ['分類設計', '例外処理', 'データ保全', '検証可能性'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'PROMPT_CONDITION',
    nextCandidates: ['WAIT'],
  },
  {
    key: 'MANAGER_PROCESS_REVIEW',
    title: '業務をAIと棚卸しする',
    phaseKey: 'PRACTICE',
    learningObjective: '業務の手順・担当・時間・問題を構造化できる',
    businessScenario: '毎週行う定型業務を見直す前に現状を整理します。',
    task: '業務名と概要を示し、手順・担当・所要時間・困りごとを表にする指示を書いてください。',
    constraints: ['現状と推測を分ける', '不足情報は質問させる', '表形式'],
    successCriteria: ['現状が工程別に見える', '問題箇所が特定できる', '不明点が区別される'],
    commonMistakes: ['最初から改善案だけ求める', '現状の担当や時間がない'],
    evaluationCriteria: ['業務分解', '情報整理', '不明情報の扱い', '実務適合性'],
    estimatedMinutes: 10,
    difficulty: 'STANDARD',
    reviewMissionKey: 'PROMPT_FORMAT',
    nextCandidates: ['MANAGER_IMPROVEMENT'],
  },
  {
    key: 'MANAGER_IMPROVEMENT',
    title: '実行できる業務改善案を作る',
    phaseKey: 'APPLICATION',
    learningObjective: '現状・制約・評価基準を示して改善案を比較できる',
    businessScenario: '棚卸しした業務から、1か月で試せる改善を選びます。',
    task: '改善対象、使える時間、予算、変えられない条件を示し、3案を比較する指示を書いてください。',
    constraints: ['案は3つ', '効果・工数・リスクで比較', '1か月以内に試せる', '最終判断は人が行う'],
    successCriteria: ['制約が明確', '案を同じ軸で比較', '試行手順がある'],
    commonMistakes: ['理想論だけを求める', 'リスクや工数を比較しない'],
    evaluationCriteria: ['課題設定', '制約指定', '比較設計', '実行可能性'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'MANAGER_PROCESS_REVIEW',
    nextCandidates: ['MANAGER_AI_DESIGN'],
  },
  {
    key: 'MANAGER_AI_DESIGN',
    title: '安全なAI活用手順を設計する',
    phaseKey: 'APPLICATION',
    learningObjective: 'AI処理と人の確認を含む実務フローを設計できる',
    businessScenario: '定型文書の下書きへAIを導入します。',
    task: '入力、AI処理、人の確認、保存、利用の順で安全な手順を作る指示を書いてください。',
    constraints: ['機密情報の扱いを明記', '人の承認工程を含む', '失敗時の戻し方を含む'],
    successCriteria: ['責任分界が明確', '確認工程がある', '例外時の対応がある'],
    commonMistakes: ['AI出力を自動確定する', '入力禁止情報がない'],
    evaluationCriteria: ['工程設計', '安全性', '人の責任', '例外処理'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'MANAGER_PROCESS_REVIEW',
    nextCandidates: ['MANAGER_TEAM_GUIDANCE'],
  },
  {
    key: 'MANAGER_TEAM_GUIDANCE',
    title: '部下へのAI活用指示を作る',
    phaseKey: 'APPLICATION',
    learningObjective: '目的・許可範囲・禁止事項・確認方法を伝えられる',
    businessScenario: 'チームで議事録作成にAIを試験導入します。',
    task: '部下向けに、使う目的、入力禁止情報、確認手順、相談先を含む指示を作ってください。',
    constraints: ['A4半ページ相当', '禁止だけでなく実施手順を書く', '責任者を明記'],
    successCriteria: ['目的と範囲が明確', '禁止事項が具体的', '確認と相談方法がある'],
    commonMistakes: ['自己責任で終わる', '禁止事項だけで使い方がない'],
    evaluationCriteria: ['方針の明確さ', '安全性', '実行手順', '支援体制'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'MANAGER_AI_DESIGN',
    nextCandidates: ['MANAGER_AI_RULES'],
  },
  {
    key: 'MANAGER_AI_RULES',
    title: '現場で守れるAI利用ルールを作る',
    phaseKey: 'APPLICATION',
    learningObjective: '許可・禁止・確認・事故対応を含む運用ルールを作れる',
    businessScenario: '小規模チーム向けのAI利用ルール初版を作ります。',
    task: '利用目的、入力禁止情報、出力確認、保存、問題発生時の連絡を含むルール作成指示を書いてください。',
    constraints: [
      '10項目以内',
      '具体例を2つ含む',
      '法的断定をさせない',
      '責任者レビューを前提にする',
    ],
    successCriteria: ['日常で判断できる', '禁止と許可が区別', '問題時の行動が分かる'],
    commonMistakes: ['抽象的な注意だけ', '全利用を禁止する', '事故対応がない'],
    evaluationCriteria: ['網羅性', '具体性', '安全性', '運用可能性'],
    estimatedMinutes: 12,
    difficulty: 'CHALLENGE',
    reviewMissionKey: 'MANAGER_AI_DESIGN',
    nextCandidates: ['WAIT'],
  },
  {
    key: 'RECOVERY',
    title: '3分でAI研修を再開する',
    phaseKey: 'FOUNDATION',
    learningObjective: '負担の小さい一歩から学習を再開できる',
    businessScenario: 'しばらく研修を開いていなかった状態から戻ります。',
    task: '今の仕事でAIに手伝ってほしいことを、短い1文で書いてください。',
    constraints: ['1文だけ', '個人情報を書かない', '完璧な指示にしなくてよい'],
    successCriteria: ['仕事の場面が1つある', 'AIへ頼みたいことが分かる'],
    commonMistakes: ['再開時から長い回答を作ろうとする', '仕事と関係のない一般論を書く'],
    evaluationCriteria: ['再開しやすさ', '作業の具体性'],
    estimatedMinutes: 3,
    difficulty: 'EASY',
    reviewMissionKey: 'RECOVERY',
    nextCandidates: ['AI_BASIC', 'PROMPT_REVIEW'],
  },
  {
    key: 'WAIT',
    title: '今日は実践結果を待つ',
    phaseKey: 'PRACTICE',
    learningObjective: '不要な課題を増やさず、実務で試した結果を待つ',
    businessScenario: '前の課題を実務で試した直後のため、新しい課題を増やしません。',
    task: '今日は新しい回答を作る必要はありません。実務で試した結果を確認してください。',
    constraints: [],
    successCriteria: ['指定時刻まで新しい課題を増やさない'],
    commonMistakes: ['待機中に別の必須課題を追加する'],
    evaluationCriteria: [],
    estimatedMinutes: 1,
    difficulty: 'EASY',
    reviewMissionKey: null,
    nextCandidates: [],
  },
] as const satisfies readonly Omit<TrainingMissionQualityDefinition, 'skillKeys'>[];

export const AI_TRAINING_MISSION_QUALITY = baseDefinitions.map((definition) => ({
  ...definition,
  skillKeys: AI_TRAINING_MISSION_SKILLS[definition.key],
})) satisfies readonly TrainingMissionQualityDefinition[];

export function getAiTrainingMissionQuality(key: string): TrainingMissionQualityDefinition | null {
  return AI_TRAINING_MISSION_QUALITY.find((definition) => definition.key === key) ?? null;
}
