ALTER TYPE "ProductionGateCheckKey" ADD VALUE IF NOT EXISTS 'DAILY_MISSION_LINE_SMOKE';
ALTER TYPE "ProductionGateCheckKey" ADD VALUE IF NOT EXISTS 'TRACKING_LINK_NOTIFICATION_SMOKE';
ALTER TYPE "ProductionGateCheckKey" ADD VALUE IF NOT EXISTS 'REFERRAL_SHARE_SMOKE';
ALTER TYPE "ProductionGateCheckKey" ADD VALUE IF NOT EXISTS 'DUPLICATE_PREVENTION_SMOKE';
